# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='新闻标题')),
                ('summary', models.CharField(max_length=255, verbose_name='新闻简介')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='新闻内容')),
            ],
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('ctime', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('solution', models.TextField(null=True)),
                ('ptime', models.DateTimeField(null=True)),
                ('pj', models.IntegerField(choices=[(1, '不满意'), (2, '一般'), (3, '满意')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articledetail',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='updown',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='updown',
            name='article',
        ),
        migrations.RemoveField(
            model_name='updown',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfans',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfans',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfans',
            name='user',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='article',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='up_count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='fans',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auth_article', to='repository.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'Html'), (4, 'Ajax')], default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='pick',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='repository.Article2Tag', to='repository.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(default='/static/imgs/avatar/default.png', max_length=255, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([('article', 'tag')]),
        ),
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UpDown',
        ),
        migrations.DeleteModel(
            name='UserFans',
        ),
        migrations.AddField(
            model_name='trouble',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_news', to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.NewsContent'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleContent'),
        ),
    ]
