# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180803_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=32, upload_to='static/upload', verbose_name='图片路径')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '图片',
            },
        ),
    ]
