# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='static/imgs/photo', verbose_name='图片路径'),
        ),
    ]
