# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180806_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
